### ISSUE TITLE
친바 참여하는 🐣 들을 위한 실전 문제 1

### ISSUE THREAD

**Issue by keinn51** [keinn51/React-Study#14]
[frontend/AttendeeList.tsx at develop · Together42/frontend](https://github.com/Together42/frontend/blob/develop/src/components/Main/AttendeeList.tsx)

아래 코드는 위의 AttendeeList 에 있는 컴포넌트를 가져온 것이에요~

<img width="650" alt="스크린샷 2022-07-24 오후 5 31 59" src="https://user-images.githubusercontent.com/79993356/180639034-c15a06f9-3f53-4650-a4b2-1338a1a5fcc5.png">

이 사진에 해당하는 컴포넌트지요. 이제 실전 코드를 읽어보면서 이해해봅니다. 다만 이제 기본이 충실히 잡혀있기 때문에 세세한 라이브러리를 알려드리지는 않을 겁니다. (타입스크립트도 읽어보셨다고 판단!) 

따라서 PBL의 느낌으로, 코드를 보고 질문을 한 후 그에 대한 답을 하도록 합니다.

```jsx
import React from 'react';
import '@css/Main/AttendeeList.scss';
import AttendeeListProfile from '@main/AttendeeListProfile';
import { useRecoilValue } from 'recoil';
import SelectedEvent from '@recoil/MainSelectedEvent';
import useSWR from 'swr';
import { EventType, teamMemInfo } from '@usefulObj/types';
import fetcher from '@globalObj/function/fetcher';
import getAddress from '@globalObj/function/getAddress';

function AttendeeList() {
  const selectedEvent = useRecoilValue(SelectedEvent);
  const { data: teamList } = useSWR<{
    event: EventType;
    teamList: { [x: string]: teamMemInfo[] };
  }>(selectedEvent ? `${getAddress()}/api/together/${selectedEvent.id}` : null, fetcher, {
    dedupingInterval: 600000,
  });
  const showAttendeeList =
    selectedEvent &&
    teamList &&
    teamList.teamList &&
    teamList.teamList.null &&
    Object.keys(teamList.teamList).length > 0;

  return (
    <div className={`main--attendeeList ${!showAttendeeList && 'data_none_div'}`}>
      <p className={`main--attendeeList--title ${!showAttendeeList && 'data_none_title'}`}>
        {showAttendeeList ? `${selectedEvent.title} 에 신청한 사서는?` : '친바 많이 신청해주세요..'}
      </p>
      {showAttendeeList && selectedEvent.id ? (
        <div className="main--attendeeList--profiles">
          {teamList.teamList.null.map((e) => (
            <AttendeeListProfile intraID={e.intraId} image={e.profile} key={e.intraId} />
          ))}
        </div>
      ) : null}
    </div>
  );
}

export default AttendeeList;
```

`@main` 은 `../../../main.c` 이런 것을 그냥 축약해서 쓸 수 있는 것입니다. (`tsconfig.json`에 있음) 그건 제외하고 이 코드에서는 **타입스크립트**와 **SWR**이라는 라이브러리가 쓰였습니다. 해당 코드를 읽고 아래의 답을 적어서 issue comment 로 달아주세요~

반환되는 html 코드들은 보실 필요 없습니다. 최대한 자세히 얘기해주세요!

### 2. 타입스크립트가 어떤 문법을 쓰고 어떤 type 으로 지정되어 적용되는지 말해주십셔

이를 통해

- 누군가의 react 코드를 읽을 수 있는 능력
- 라이브러리의 사용법을 찾는 서칭 능력
- 코드 구동을 설명할 수 있는 능력

이 생길 것입니당! 코멘트는 아래의 이슈에서 달아주세요~

**Comment by 2Yebeen** [comment]
0. useSWR : 
`npm install swr / yarn add swr`
`import useSWR from 'swr';`
`const { data, error, isValidating, mutate } = useSWR(key, fetcher, options)`

1. swr는 데이터를 가져오기 위한 React의 Hook입니다. 먼저 캐시로부터 데이터(오래된)를 먼저 반환을 해주고 그다음 fetch(재검증) 후 업데이트된 데이터를 반환합니다. 즉, swr를 사용하면 컴포넌트는 지속적이며 자동으로 데이터 업데이트를 통해 UX의 향상을 만들어 낼 수 있습니다. 
`const { data : type } = useSWR<type>(shouldFetch ? '/api/data' : null, fetcher, option)`
문제에서는 selectedEvent 값에 따라 null을 사용하거나 함수를 key로 전달하여 데이터를 조건부로 가져옵니다. 이때 dedupingInterval 옵션으로 시간 범위 내에 동일 키를 사용하는 요청의 중복을 제거합니다. 

2. 타입스크립트는 식별자 또는 값 뒤에 콜론(:)을 붙여 코드에서 어떤 변수 또는 값의 타입을 표기합니다. 
useSWR로 받아오는 data는 teamList 타입으로 지정되어 있습니다.
useSWR의 경우 event의 타입은 EventType, teamList의 경우 teamMemInfo 배열 타입을 가지며 인덱스는 string 타입으로 지정되어 있습니다.
 
자바스크립트를 하면서 잘못된 부분을 찾기가 어려웠는데 타입스크립트를 통해서 코드를 돌리기 전에 에러를 미리 잡을 수 있을 것 같습니다.

**Comment by yenawee** [comment]
1. 해당 코드에서 SWR이 어떤 역할을 하고, 어떻게 쓰이고 있는지 말해주세욤

selectedEvent 가 true 일때 "${getAddress()}/api/together/${selectedEvent.id}" 로 API 요청을 보내서 응답받은 데이터를 data 에 저장한다
fetcher는 SWR의 key를 받고 데이터를 반환하는 비동기 함수이고 
옵션 dedupingInterval = 600000: 이 시간 범위내에 동일 키를 사용하는 요청 중복 제거(단위 : milliseconds)

<사용 문법>
`const { data, error, isValidating, mutate } = useSWR(key, fetcher, options)`

<장점>
- 데이터 가져오기를 위한 React hook 으로 컴포넌트는 지속적이며 자동으로 빠르고 반응적으로 데이터 업데이트 스트림을 받을 수 있다.
   -   axios는 한 번 get으로 호출을 하면 다시 호출하지 않는 이상 이전의 데이터를 그대로 유지한다.
   -   swr은 최초 한 번만 호출해도 다른 곳으로 포커싱을 옮겼다가 다시 포커싱하면 새로운 데이터로 갱신됨.
 -  동일한 SWR 키를 사용하면 동일한 API 요청이 여러 번 호출될 경우 그 요청이 자동으로 중복 제거, 캐시, 공유되므로, 단 한 번의 요청만 API로 전송된다(한번만 실행)

2. 타입스크립트가 어떤 문법을 쓰고 어떤 type 으로 지정되어 적용되는지 말해주십셔

SWR 에 타입 지정
ex > `const { data } = useSWR<type>('/api/data', fetcher, config)`

data 는 event 랑 teamList 를 속성으로 갖는 teamList 타입인데 그 타입은
event 속성은 user define 한 EventType 쓰고 
teamList 속성은 key 값이 string type, value값이 user define 한 teamMeminfo 타입 쓰는 객체다

**Comment by keinn51** [comment]
@yenawee

> 1. 해당 코드에서 SWR이 어떤 역할을 하고, 어떻게 쓰이고 있는지 말해주세욤
> 
> selectedEvent 가 true 일때 "getAddress()/api/together/{selectedEvent.id}" 로 API 요청을 보내서 응답받은 데이터를 data 에 저장한다 fetcher는 SWR의 key를 받고 데이터를 반환하는 비동기 함수이고 옵션 dedupingInterval = 600000: 이 시간 범위내에 동일 키를 사용하는 요청 중복 제거(단위 : milliseconds)

단위까지 넣어서 찾아오시다니 훌륭하십니다.. 

> <사용 문법> `const { data, error, isValidating, mutate } = useSWR(key, fetcher, options)`
> 
> <장점>
> 
> * 데이터 가져오기를 위한 React hook 으로 컴포넌트는 지속적이며 자동으로 빠르고 반응적으로 데이터 업데이트 스트림을 받을 수 있다.
>   
>   * axios는 한 번 get으로 호출을 하면 다시 호출하지 않는 이상 이전의 데이터를 그대로 유지한다.
>   * swr은 최초 한 번만 호출해도 다른 곳으로 포커싱을 옮겼다가 다시 포커싱하면 새로운 데이터로 갱신됨.
> * 동일한 SWR 키를 사용하면 동일한 API 요청이 여러 번 호출될 경우 그 요청이 자동으로 중복 제거, 캐시, 공유되므로, 단 한 번의 요청만 API로 전송된다(한번만 실행)
 
axios 장점도 잘 찾아오셨어요 그런 장점이 있어서 쓰는거랍니다 🙂
그리고 동일한 요청의 경우 자동으로 중복 제거가 되는게 아주 좋아욤~

> 2. 타입스크립트가 어떤 문법을 쓰고 어떤 type 으로 지정되어 적용되는지 말해주십셔
> 
> SWR 에 타입 지정 ex > `const { data } = useSWR<type>('/api/data', fetcher, config)`
> 
> data 는 event 랑 teamList 를 속성으로 갖는 teamList 타입인데 그 타입은 event 속성은 user define 한 EventType 쓰고 teamList 속성은 key 값이 string type, value값이 user define 한 teamMeminfo 타입 쓰는 객체다

 타입 지정도 확실히 이해한 것 같아서 너무 좋습니다 ☺️ 이제 확실히 리액트 많은 부분을 아시는 것 같아서 당장 투입되어도 손색이 없으실 것 같아요 🤗 미니셸 하시면서도 리액트 공부 잘 해오신 것 지금 보니 아주 대단한 일이었다는 생각이 듭니다 😱 수고 많으셨어욥

**Comment by keinn51** [comment]
@yeblee 

> 0. useSWR :
>    `npm install swr / yarn add swr`
>    `import useSWR from 'swr';`
>    `const { data, error, isValidating, mutate } = useSWR(key, fetcher, options)`
> 1. swr는 데이터를 가져오기 위한 React의 Hook입니다. 먼저 캐시로부터 데이터(오래된)를 먼저 반환을 해주고 그다음 fetch(재검증) 후 업데이트된 데이터를 반환합니다. 즉, swr를 사용하면 컴포넌트는 지속적이며 자동으로 데이터 업데이트를 통해 UX의 향상을 만들어 낼 수 있습니다.

지속적으로 데이터 업데이트를 통해 UX의 향상을 가져온다는 것이 무슨 말인지 이해하셨나요?? 

>    `const { data : type } = useSWR<type>(shouldFetch ? '/api/data' : null, fetcher, option)`
>    문제에서는 selectedEvent 값에 따라 null을 사용하거나 함수를 key로 전달하여 데이터를 조건부로 가져옵니다. 이때 dedupingInterval 옵션으로 시간 범위 내에 동일 키를 사용하는 요청의 중복을 제거합니다.

문제 코드에 대한 해석을 잘 해오신 것 같아요! 수고 많으셨습니다 😀

> 2. 타입스크립트는 식별자 또는 값 뒤에 콜론(:)을 붙여 코드에서 어떤 변수 또는 값의 타입을 표기합니다.
>    useSWR로 받아오는 data는 teamList 타입으로 지정되어 있습니다.
>    useSWR의 경우 event의 타입은 EventType, teamList의 경우 teamMemInfo 배열 타입을 가지며 인덱스는 string 타입으로 지정되어 있습니다.
> 
> 자바스크립트를 하면서 잘못된 부분을 찾기가 어려웠는데 타입스크립트를 통해서 코드를 돌리기 전에 에러를 미리 잡을 수 있을 것 같습니다.

예블리님은 과제 처리 능력이 정말 빠른 것 같아요. 그리고 여러 일을 처리하면서도 꾸준히 잘 해결해나가시는 모습을 보니까 정말 능력이 있는 분이신 것 같아서 대단합니다 👍 중요한 내용 잘 공부해 오셨구 수고 많으셨습니다 🤟
